import React from 'react';
import Any from '../any.jsx';
import Popup from './popup-base.jsx';
import Form from './form.jsx';
import Input from './input.jsx';
import A from './a.jsx';

class PopupPut2fa extends Any {
	constructor(props) {
		super(props);
		this.setState({code2fa:""});
	}
	render(p,s,c,m) {
		var content = <div>
			<h1 className="h1-center mt-0">ENTER 2-FACTOR <br />AUTHENTICATION CODE</h1>
			<p>
				<img
					src="img/set2fa-popup.png" width="65" height="105"
					style={{float:"left",marginRight:"18px",position:"relative",top:"-3px"}}
				/>
				Please enter the 6-digit code generated by the authentication app on your device to verify the transaction
			</p>
			<Form onSubmit={this.onSubmit.bind(this)}>
				<Input
					type="text" placeholder="AUTHENTICATION CODE"
					hint={s.pending ? "Loading...": s.er ? s.er.message : "E.g. 123 456"}
					value={s.code2fa} onChange={(this.onCode.bind(this))}
					hasError={s.codeValid==false || s.er}
					checkValid={str=>(str+'').replace(/\D+/g, "").length==6} required
				/>
				<div className="d-flex flex-column align-items-center justify-content-center mt-4">
					<button type="submit"
						disabled={!s.codeValid || s.pending}
						className={[
							"btn btn-lg btn-primary", "mb-3",
							s.codeValid ? "" : " disabled",
						].join(" ")}
					>
						SEND
					</button>
					<A m={m} className="text-muted external"><small>I’m not able to log in with 2FA</small></A>
				</div>
			</Form>
		</div>;
		return this.renderWrap(p,s,content,m);
	}
	renderWrap(p,s,c,m) {
		if (p.noPopup) {
			return <div>{c}</div>;
		} else {
			return <Popup onClose={p.onClose}>{c}</Popup>;
		}
	}
	onCode(code2fa,codeValid) {
		this.setState({code2fa,codeValid,er:null}, ()=>{
			this.forceUpdate();
		});
	}
	onSubmit() {
		this.setState({pending:true});
		this.props.m.api.login2fa(this.state.code2fa)
		.then(x=>{
			this.props.onClose();
		})
		.catch(er=>{
			this.setState({er,pending:false})
		})
	}
}

export default PopupPut2fa;
